/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Text = string;
export type Timestamp = string;
export type FeedId = string;
export type Digest = string;
/**
 * @minItems 1
 * @maxItems 64
 */
export type Paragraphs = [Text, ...Text[]];
export type Callout =
  | {
      kind: "quote";
      text: Text;
      attribution: Text;
      attribution_source: Text;
    }
  | {
      kind: "figure";
      value: Text;
      label: Text;
    }
  | {
      kind: "facts";
      title: Text;
      /**
       * @minItems 2
       * @maxItems 4
       */
      items: [Text, Text] | [Text, Text, Text] | [Text, Text, Text, Text];
    }
  | {
      kind: "box";
      label: Text;
      text: Text;
    }
  | {
      kind: "timeline";
      title: Text;
      /**
       * @minItems 2
       * @maxItems 4
       */
      rows:
        | [
            {
              date: Text;
              text: Text;
            },
            {
              date: Text;
              text: Text;
            },
          ]
        | [
            {
              date: Text;
              text: Text;
            },
            {
              date: Text;
              text: Text;
            },
            {
              date: Text;
              text: Text;
            },
          ]
        | [
            {
              date: Text;
              text: Text;
            },
            {
              date: Text;
              text: Text;
            },
            {
              date: Text;
              text: Text;
            },
            {
              date: Text;
              text: Text;
            },
          ];
    };

export interface EditionContractV1 {
  schema_version: 1;
  title: Id;
  edition: Edition;
  presentation?: Presentation;
  coverage: Coverage;
  /**
   * @maxItems 128
   */
  inputs: Input[];
  /**
   * @minItems 1
   * @maxItems 64
   */
  stories: [Story, ...Story[]];
  fit_policy: FitPolicy;
}
export interface Edition {
  id: Id;
  number: number;
  name: Text;
  date: string;
  timezone: "Europe/Copenhagen";
  language: "en" | "da";
  cutoff_at: Timestamp;
  generated_at: Timestamp;
}
export interface Presentation {
  preferred_composition?: "lead-wide" | "lead-tall" | "lead-centred";
  emphasis?: "one_big_story" | "quiet_day" | "many_stories";
  ear_right?: Text;
}
export interface Coverage {
  status: "complete" | "partial" | "unknown";
  checked_from: Timestamp;
  checked_until: Timestamp;
  note: Text;
  /**
   * @maxItems 256
   */
  feeds: Feed[];
}
export interface Feed {
  feed_id: FeedId;
  source: Id;
  outcome: "checked" | "failed" | "not_checked";
  last_checked_at: Timestamp | null;
}
export interface Input {
  id: Id;
  sha256: Digest;
}
export interface Story {
  id: Id;
  device_participation: "required" | "optional" | "reserve";
  role: "lead" | "secondary" | "brief";
  fallback_role?: "brief";
  kicker: Text;
  kicker_secondary?: Text;
  copy: Copy;
  /**
   * @maxItems 16
   */
  callouts:
    | []
    | [Callout]
    | [Callout, Callout]
    | [Callout, Callout, Callout]
    | [Callout, Callout, Callout, Callout]
    | [Callout, Callout, Callout, Callout, Callout]
    | [Callout, Callout, Callout, Callout, Callout, Callout]
    | [Callout, Callout, Callout, Callout, Callout, Callout, Callout]
    | [Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout]
    | [Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout]
    | [Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout]
    | [Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout]
    | [Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout, Callout]
    | [
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
      ]
    | [
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
      ]
    | [
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
      ]
    | [
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
        Callout,
      ];
  /**
   * @maxItems 16
   */
  sources:
    | []
    | [Source]
    | [Source, Source]
    | [Source, Source, Source]
    | [Source, Source, Source, Source]
    | [Source, Source, Source, Source, Source]
    | [Source, Source, Source, Source, Source, Source]
    | [Source, Source, Source, Source, Source, Source, Source]
    | [Source, Source, Source, Source, Source, Source, Source, Source]
    | [Source, Source, Source, Source, Source, Source, Source, Source, Source]
    | [Source, Source, Source, Source, Source, Source, Source, Source, Source, Source]
    | [Source, Source, Source, Source, Source, Source, Source, Source, Source, Source, Source]
    | [Source, Source, Source, Source, Source, Source, Source, Source, Source, Source, Source, Source]
    | [Source, Source, Source, Source, Source, Source, Source, Source, Source, Source, Source, Source, Source]
    | [Source, Source, Source, Source, Source, Source, Source, Source, Source, Source, Source, Source, Source, Source]
    | [
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
      ]
    | [
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
        Source,
      ];
  limitations: (
    "digest_of_rss_description" | "translated_from_source_language" | "headline_only" | "partial_source_coverage"
  )[];
}
export interface Copy {
  headline: Text;
  headline_short?: Text;
  deck?: Text;
  lede?: Text;
  body: Body;
}
export interface Body {
  extended?: Paragraphs;
  standard?: Paragraphs;
  short?: Paragraphs;
}
export interface Source {
  source: Id;
  source_id: Text;
  input_id: Id;
  original_title: Text;
  url: string;
  published_at: Timestamp;
  content_hash: Digest;
  primary: boolean;
}
export interface FitPolicy {
  allow_role_fallback: boolean;
  allow_composition_substitution: boolean;
  reserve_story_ids: Id[];
  omittable_story_ids: Id[];
}
